In [1]:
# importing all necessary libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

In [2]:
df=pd.read_csv("CARS DATA.CSV")

In [3]:
df

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [4]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [5]:
df['Engine Fuel Type'].fillna("premium unleaded (required)",inplace=True)
df.drop('Market Category',axis=1,inplace=True)
df['Number of Doors'].fillna(2.0,inplace=True)
df['Engine HP'].fillna(df['Engine HP'].median(),inplace=True)

In [6]:
df['Engine Cylinders'].fillna(4.0,inplace=True)

In [7]:
df.dtypes

Make                  object
Model                 object
Year                   int64
Engine Fuel Type      object
Engine HP            float64
Engine Cylinders     float64
Transmission Type     object
Driven_Wheels         object
Number of Doors      float64
Vehicle Size          object
Vehicle Style         object
highway MPG            int64
city mpg               int64
Popularity             int64
MSRP                   int64
dtype: object

In [8]:
ln=LabelEncoder()

In [9]:
df['Make_encode']=ln.fit_transform(df['Make'])

In [10]:
df['Engine Fuel Type_encode']=ln.fit_transform(df['Engine Fuel Type'])

In [11]:
df['Transmission Type_encode']=ln.fit_transform(df['Transmission Type'])

In [12]:
df['Driven_Wheels_encode']=ln.fit_transform(df['Driven_Wheels'])

In [13]:
df['Vehicle Size_encode']=ln.fit_transform(df['Vehicle Size'])

In [14]:
df['Vehicle Style_encode']=ln.fit_transform(df['Vehicle Style'])

In [15]:
df['Model_encode']=ln.fit_transform(df['Model'])

In [16]:
df[['Engine HP','Engine Cylinders','Number of Doors','highway MPG','city mpg','Popularity','Make_encode','Engine Fuel Type_encode','Transmission Type_encode','Driven_Wheels_encode','Vehicle Size_encode','Vehicle Style_encode','Model_encode','MSRP']].corr()

Engine HP  Engine Cylinders  Number of Doors  \
Engine HP                  1.000000          0.767602        -0.103384   
Engine Cylinders           0.767602          1.000000        -0.138648   
Number of Doors           -0.103384         -0.138648         1.000000   
highway MPG               -0.359457         -0.607422         0.110819   
city mpg                  -0.353894         -0.574382         0.113032   
Popularity                 0.036823          0.042431        -0.048276   
Make_encode               -0.226445         -0.265040         0.056081   
Engine Fuel Type_encode   -0.194705         -0.073176        -0.001178   
Transmission Type_encode  -0.238357         -0.166611        -0.335509   
Driven_Wheels_encode      -0.035007          0.084847        -0.252479   
Vehicle Size_encode        0.207912          0.197754         0.266882   
Vehicle Style_encode       0.013490          0.034029         0.201647   
Model_encode               0.001831          0.066346         0.138336   
MSRP                       0.661402          0.531171        -0.127521   

                          highway MPG  city mpg  Popularity  Make_encode  \
Engine HP                   -0.359457 -0.353894    0.036823    -0.226445   
Engine Cylinders            -0.607422 -0.574382    0.042431    -0.265040   
Number of Doors              0.110819  0.113032   -0.048276     0.056081   
highway MPG                  1.000000  0.886829   -0.020991     0.133242   
city mpg                     0.886829  1.000000   -0.003217     0.150862   
Popularity                  -0.020991 -0.003217    1.000000    -0.297651   
Make_encode                  0.133242  0.150862   -0.297651     1.000000   
Engine Fuel Type_encode     -0.171557 -0.184718   -0.059357     0.115637   
Transmission Type_encode     0.044252  0.048807    0.010095     0.045022   
Driven_Wheels_encode        -0.003503 -0.011236    0.026987    -0.035689   
Vehicle Size_encode         -0.111000 -0.142728   -0.003995    -0.102262   
Vehicle Style_encode         0.027447 -0.041795    0.036024    -0.057137   
Model_encode                -0.104276 -0.035716   -0.073725     0.037819   
MSRP                        -0.160043 -0.157676   -0.048476    -0.107331   

                          Engine Fuel Type_encode  Transmission Type_encode  \
Engine HP                               -0.194705                 -0.238357   
Engine Cylinders                        -0.073176                 -0.166611   
Number of Doors                         -0.001178                 -0.335509   
highway MPG                             -0.171557                  0.044252   
city mpg                                -0.184718                  0.048807   
Popularity                              -0.059357                  0.010095   
Make_encode                              0.115637                  0.045022   
Engine Fuel Type_encode                  1.000000                  0.123549   
Transmission Type_encode                 0.123549                  1.000000   
Driven_Wheels_encode                     0.019017                  0.173338   
Vehicle Size_encode                     -0.049178                 -0.305262   
Vehicle Style_encode                    -0.044330                 -0.035039   
Model_encode                            -0.010334                 -0.074973   
MSRP                                    -0.114732                 -0.181742   

                          Driven_Wheels_encode  Vehicle Size_encode  \
Engine HP                            -0.035007             0.207912   
Engine Cylinders                      0.084847             0.197754   
Number of Doors                      -0.252479             0.266882   
highway MPG                          -0.003503            -0.111000   
city mpg                             -0.011236            -0.142728   
Popularity                            0.026987            -0.003995   
Make_encode                          -0.035689            -0.102262   
Engine Fuel Type_enc

In [34]:
x=df[['Make_encode','Model_encode','Year','Engine Cylinders']]
y=df['MSRP']


In [35]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=2529)

In [36]:
rf=RandomForestRegressor()

In [37]:
rf.fit(x_train,y_train)

RandomForestRegressor()

In [38]:
lr=LinearRegression()

In [39]:
lr.fit(x_train,y_train)

LinearRegression()

In [40]:
rf.score(x_train,y_train)

0.9782204200805946

In [41]:
rf.score(x_test,y_test)

0.9382138123495716

In [42]:
x_test.iloc[0]

Make_encode           47.0
Model_encode         838.0
Year                2016.0
Engine Cylinders       5.0
Name: 11137, dtype: float64

In [43]:
rf.predict(x_test)

array([41654.86      , 31233.33237325, 57078.93330281, ...,
       26233.87160617, 47622.745     ,  2050.26      ])

In [44]:
import pickle

In [48]:
# Save the model to a file using pickle
with open('model.pkl', 'wb') as model_file:
    pickle.dump(lr, model_file)

In [46]:
df['Year'].unique()

array([2011, 2012, 2013, 1992, 1993, 1994, 2017, 1991, 2016, 1990, 2015,
       1996, 1997, 1998, 2014, 1999, 2002, 2003, 2004, 1995, 2007, 2008,
       2009, 2001, 2010, 2000, 2005, 2006], dtype=int64)

In [47]:
df['Make'][df['Make_encode']==47]

104      Volvo
105      Volvo
106      Volvo
107      Volvo
108      Volvo
         ...  
11636    Volvo
11637    Volvo
11638    Volvo
11639    Volvo
11640    Volvo
Name: Make, Length: 281, dtype: object

In [31]:
df['Model'][df['Model_encode']==838]

11121    V60
11122    V60
11123    V60
11124    V60
11125    V60
11126    V60
11127    V60
11128    V60
11129    V60
11130    V60
11131    V60
11132    V60
11133    V60
11134    V60
11135    V60
11136    V60
11137    V60
11138    V60
11139    V60
11140    V60
11141    V60
Name: Model, dtype: object

In [32]:
df['Make'].unique()

array(['BMW', 'Audi', 'FIAT', 'Mercedes-Benz', 'Chrysler', 'Nissan',
       'Volvo', 'Mazda', 'Mitsubishi', 'Ferrari', 'Alfa Romeo', 'Toyota',
       'McLaren', 'Maybach', 'Pontiac', 'Porsche', 'Saab', 'GMC',
       'Hyundai', 'Plymouth', 'Honda', 'Oldsmobile', 'Suzuki', 'Ford',
       'Cadillac', 'Kia', 'Bentley', 'Chevrolet', 'Dodge', 'Lamborghini',
       'Lincoln', 'Subaru', 'Volkswagen', 'Spyker', 'Buick', 'Acura',
       'Rolls-Royce', 'Maserati', 'Lexus', 'Aston Martin', 'Land Rover',
       'Lotus', 'Infiniti', 'Scion', 'Genesis', 'HUMMER', 'Tesla',
       'Bugatti'], dtype=object)

In [97]:
df['Model'][df['Make']=="Tesla"].unique()

array(['Model S'], dtype=object)

In [98]:
df["Year"].unique()

array([2011, 2012, 2013, 1992, 1993, 1994, 2017, 1991, 2016, 1990, 2015,
       1996, 1997, 1998, 2014, 1999, 2002, 2003, 2004, 1995, 2007, 2008,
       2009, 2001, 2010, 2000, 2005, 2006], dtype=int64)